changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🚀 Features
      labels:
        - enhancement
        - feature
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🧰 Maintenance
      labels:
        - chore
        - ci
        - refactor
        - test
        - docs
    - title: Other Changes
      labels:
        - "*"
