#!/bin/sh
printf 'osascript %s\n' "$*" >> "$SHIMLOG"
if [ -n "$SHIMAPPLY" ]; then
  id=$(printf '%s' "$2" | /usr/bin/sed -n 's/.* id "\([^"]*\)".*/\1/p')
  case "$2" in *"to completed"*) st=3;; *"to canceled"*) st=2;; *) exit 0;; esac
  /usr/bin/sqlite3 "$SHIMDB" "UPDATE TMTask SET status=$st, stopDate=1760100000, userModificationDate=1760100001 WHERE uuid='$id';"
fi
exit 0
